<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyHeroesClicker.Browser\MyHeroesClicker.Browser.csproj" />
    <ProjectReference Include="..\MyHeroesClicker.Core\MyHeroesClicker.Core.csproj" />
    <ProjectReference Include="..\MyHeroesClicker.DataSQLite\MyHeroesClicker.DataSQLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
