<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MyHeroesClicker.Launcher</AssemblyName>
    <RootNamespace>MyHeroesClicker.Launcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.0.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyHeroesClicker.API\MyHeroesClicker.API.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\MyHeroesClicker.DbMigrator\MyHeroesClicker.DbMigrator.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
